// Auto-generated type from docs/RESOURCES_ACTIONS_MATRIX.md
import { Resource } from '../enums/resource.enum';
import { Action } from '../enums/action.enum';

export type ResourceType = 'collection' | 'item';

export type ResourceMeta = {
  type: ResourceType;
  actions: Action[];
};

export const RESOURCE_META: Record<Resource, ResourceMeta> = {
  [Resource.CONNECT_CONTACTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONNECT_CONTACTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_ASSETS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_ASSETS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_BACKGROUNDS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_BACKGROUNDS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_BACKGROUNDS_TRANSITION]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_BACKGROUNDS_TRANSITION_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_CHANNELS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_CHANNELS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_CONTENT_GROUPS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_CONTENT_GROUPS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_PLAYLISTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_PLAYLISTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_TAGS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_TAGS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_TAGS_ASSIGNMENTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_TAGS_ASSIGNMENTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.CONTENTS_TEMPLATES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.CONTENTS_TEMPLATES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.FOOTPRINTS_ENDPOINTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.FOOTPRINTS_ENDPOINTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.FOOTPRINTS_PRICING]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.FOOTPRINTS_PRODUCTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.FOOTPRINTS_PRODUCTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.FOOTPRINTS_SITES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.FOOTPRINTS_SITES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.QR_CAMPAIGNS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.QR_CAMPAIGNS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.QR_MEDIA]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.QR_MEDIA_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.QR_SITE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.QR_SITE_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.QR_TEMPLATES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.QR_TEMPLATES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.REPORTS_CAMPAIGN_COMPLIANCE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT] },
  [Resource.REPORTS_CAMPAIGN_COMPLIANCE_DETAILS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT] },
  [Resource.REPORTS_CAMPAIGN_PERFORMANCE_MAPS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT] },
  [Resource.REPORTS_CONTENT_PROOF_OF_PLAY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT] },
  [Resource.REPORTS_EXPORT]: { type: 'collection', actions: [Action.LIST, Action.EXPORT, Action.DELETE] },
  [Resource.REPORTS_MEDIA_PERFORMANCE_MAPS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT] },
  [Resource.REPORTS_QR_PERFORMANCE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT] },
  [Resource.REPORTS_QR_PERFORMANCE_SITE_TO_SITE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT] },
  [Resource.REPORTS_SITE_PERFORMANCE_MAPS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT] },
  [Resource.SETTINGS_ADMIN_CERBOS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_ADMIN_CERBOS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_ADMIN_GENERAL_AGENCY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_ADMIN_GENERAL_AMBIENT_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_ADMIN_GENERAL_BRAND_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_ADMIN_GENERAL_RETAILER_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_ADMIN_TEAMS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_ADMIN_TEAMS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_ADMIN_USERS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_ADMIN_USERS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_FOOTPRINTS_PRODUCTS_PRICING_GROUP]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_FOOTPRINTS_PRODUCTS_PRICING_GROUP_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_FOOTPRINTS_PRODUCTS_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_FOOTPRINTS_PRODUCTS_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_FOOTPRINTS_SITES_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_FOOTPRINTS_SITES_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_QR_DEFAULT_REDIRECT]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_QR_DEFAULT_REDIRECT_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_QR_DESIGN]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_QR_DESIGN_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_QR_DOMAIN]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_QR_DOMAIN_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_QR_POWER_TAG]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_QR_POWER_TAG_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_SIGNAGE_LAYOUT]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_SIGNAGE_LAYOUT_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_SIGNAGE_PEOPLE_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_SIGNAGE_PEOPLE_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_SIGNAGE_PLACES_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_SIGNAGE_PLACES_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_SIGNAGE_THINGS_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SETTINGS_SIGNAGE_THINGS_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SETTINGS_USER_PROFILE_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE] },
  [Resource.SIGNAGES_PEOPLE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SIGNAGES_PEOPLE_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SIGNAGES_PLACES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SIGNAGES_PLACES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
  [Resource.SIGNAGES_THINGS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT] },
  [Resource.SIGNAGES_THINGS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE] },
};
