// Auto-generated type from docs/RESOURCES_ACTIONS_MATRIX.md
import { Resource } from '../enums/resource.enum';
import { Action } from '../enums/action.enum';
import { Product } from '../enums/product.enum';

export type ResourceType = 'collection' | 'item';

export type ResourceMeta = {
  type: ResourceType;
  actions: Action[];
  products: Product[];
};

export const RESOURCE_META: Record<Resource, ResourceMeta> = {
  [Resource.CMS_API_KEY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_API_KEY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CMS_BLOCK]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_BLOCK_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CMS_COLLECTION]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_COLLECTION_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CMS_ENTRY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_ENTRY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CMS_FIELD]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_FIELD_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CMS_INVITATION]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_INVITATION_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CMS_PAGE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_PAGE_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CMS_SECTION]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_SECTION_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CMS_WEBSITE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CMS] },
  [Resource.CMS_WEBSITE_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CMS] },
  [Resource.CONNECT_CONTACTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.CONNECT] },
  [Resource.CONNECT_CONTACTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.CONNECT] },
  [Resource.CONTENTS_ASSETS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_ASSETS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_BACKGROUNDS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_BACKGROUNDS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_BACKGROUNDS_TRANSITION]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_BACKGROUNDS_TRANSITION_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_CHANNELS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_CHANNELS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_CONTENT_GROUPS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_CONTENT_GROUPS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_LANDING_PAGES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.LANDING] },
  [Resource.CONTENTS_LANDING_PAGES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.LANDING] },
  [Resource.CONTENTS_PLAYLISTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_PLAYLISTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE] },
  [Resource.CONTENTS_TAGS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.CONTENTS_TAGS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.CONTENTS_TAGS_ASSIGNMENTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.CONTENTS_TAGS_ASSIGNMENTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.CONTENTS_TAGS_TAXONOMY]: { type: 'collection', actions: [Action.CREATE], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.CONTENTS_TAGS_TAXONOMY_ITEM]: { type: 'item', actions: [Action.UPDATE, Action.DELETE], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.CONTENTS_TEMPLATES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PRICE_TAGS, Product.SIGNAGE] },
  [Resource.CONTENTS_TEMPLATES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.PRICE_TAGS, Product.SIGNAGE] },
  [Resource.DEALDESK_BLUEPRINTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [] },
  [Resource.DEALDESK_BRAND_USERS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.BRAND_CENTER] },
  [Resource.DEALDESK_BRAND_USERS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.BRAND_CENTER] },
  [Resource.DEALDESK_BRANDS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.BRAND_CENTER] },
  [Resource.DEALDESK_BRANDS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.BRAND_CENTER] },
  [Resource.DEALDESK_CAMPAIGNS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_CAMPAIGNS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_DSP_BLOCKS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SSP] },
  [Resource.DEALDESK_DSP_BLOCKS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SSP] },
  [Resource.DEALDESK_INVENTORY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_INVENTORY_PROVISIONING]: { type: 'collection', actions: [Action.CREATE], products: [Product.SSP] },
  [Resource.DEALDESK_LINE_ITEMS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.TRADE] },
  [Resource.DEALDESK_LINE_ITEMS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.TRADE] },
  [Resource.DEALDESK_MEDIA_PACKAGES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.TRADE] },
  [Resource.DEALDESK_MEDIA_PACKAGES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.TRADE] },
  [Resource.DEALDESK_PHOTO_VERIFICATIONS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.TRADE] },
  [Resource.DEALDESK_PHOTO_VERIFICATIONS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.TRADE] },
  [Resource.DEALDESK_PLACEMENT_RULES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_PLACEMENT_RULES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_PLACEMENT_TYPES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_PLACEMENT_TYPES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_RATE_CARDS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_REPORTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.SSP, Product.TRADE, Product.BRAND_CENTER] },
  [Resource.DEALDESK_SITES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [] },
  [Resource.DEALDESK_SSP]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE], products: [Product.SSP] },
  [Resource.DEALDESK_STORE_TRAFFIC]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SSP, Product.TRADE] },
  [Resource.DEALDESK_TRADE_LEDGERS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.TRADE] },
  [Resource.DEALDESK_TRADE_LEDGERS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.TRADE] },
  [Resource.DEALDESK_BRAND_MEDIA_PACKAGES]: { type: 'collection', actions: [Action.LIST, Action.VIEW], products: [Product.BRAND_CENTER] },
  [Resource.FOOTPRINTS_ENDPOINTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PRICE_TAGS, Product.SIGNAGE] },
  [Resource.FOOTPRINTS_ENDPOINTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.PRICE_TAGS, Product.SIGNAGE] },
  [Resource.FOOTPRINTS_PRICING]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PRICE_TAGS, Product.PRODUCT, Product.SIGNAGE] },
  [Resource.FOOTPRINTS_PRODUCTS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE] },
  [Resource.FOOTPRINTS_PRODUCTS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE] },
  [Resource.FOOTPRINTS_SITES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE] },
  [Resource.FOOTPRINTS_SITES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE] },
  [Resource.QR_CAMPAIGNS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.LANDING, Product.CONNECT, Product.PPT] },
  [Resource.QR_CAMPAIGNS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.LANDING, Product.CONNECT, Product.PPT] },
  [Resource.QR_MEDIA]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR] },
  [Resource.QR_MEDIA_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR] },
  [Resource.QR_SITE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR] },
  [Resource.QR_SITE_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR] },
  [Resource.QR_TEMPLATES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR] },
  [Resource.QR_TEMPLATES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR] },
  [Resource.REPORTS_CAMPAIGN_COMPLIANCE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.QR, Product.COMPLIANCE, Product.SIGNAGE] },
  [Resource.REPORTS_CAMPAIGN_COMPLIANCE_DETAILS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.QR, Product.COMPLIANCE, Product.SIGNAGE] },
  [Resource.REPORTS_CAMPAIGN_PERFORMANCE_MAPS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.QR, Product.COMPLIANCE, Product.SIGNAGE] },
  [Resource.REPORTS_CONTENT_PROOF_OF_PLAY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.SIGNAGE] },
  [Resource.REPORTS_EXPORT]: { type: 'collection', actions: [Action.LIST, Action.EXPORT, Action.DELETE], products: [Product.QR, Product.COMPLIANCE, Product.PRODUCT, Product.SIGNAGE, Product.CONNECT] },
  [Resource.REPORTS_MEDIA_PERFORMANCE_MAPS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.QR] },
  [Resource.REPORTS_QR_PERFORMANCE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.QR] },
  [Resource.REPORTS_QR_PERFORMANCE_SITE_TO_SITE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.QR] },
  [Resource.REPORTS_SITE_PERFORMANCE_MAPS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.EXPORT], products: [Product.QR] },
  [Resource.SETTINGS_ADMIN_CERBOS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [] },
  [Resource.SETTINGS_ADMIN_CERBOS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [] },
  [Resource.SETTINGS_ADMIN_GENERAL_AGENCY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [] },
  [Resource.SETTINGS_ADMIN_GENERAL_AMBIENT_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [] },
  [Resource.SETTINGS_ADMIN_GENERAL_BRAND_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [] },
  [Resource.SETTINGS_ADMIN_GENERAL_RETAILER_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [] },
  [Resource.SETTINGS_ADMIN_TEAMS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [] },
  [Resource.SETTINGS_ADMIN_TEAMS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [] },
  [Resource.SETTINGS_ADMIN_USERS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [] },
  [Resource.SETTINGS_ADMIN_USERS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [] },
  [Resource.SETTINGS_FOOTPRINTS_PRODUCTS_PRICING_GROUP]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PRICE_TAGS, Product.PRODUCT] },
  [Resource.SETTINGS_FOOTPRINTS_PRODUCTS_PRICING_GROUP_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.PRICE_TAGS, Product.PRODUCT] },
  [Resource.SETTINGS_FOOTPRINTS_PRODUCTS_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT] },
  [Resource.SETTINGS_FOOTPRINTS_PRODUCTS_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.PRICE_TAGS, Product.COMPLIANCE, Product.PRODUCT] },
  [Resource.SETTINGS_FOOTPRINTS_SITES_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE] },
  [Resource.SETTINGS_FOOTPRINTS_SITES_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR, Product.PRICE_TAGS, Product.COMPLIANCE] },
  [Resource.SETTINGS_QR_DEFAULT_REDIRECT]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR] },
  [Resource.SETTINGS_QR_DEFAULT_REDIRECT_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR] },
  [Resource.SETTINGS_QR_DESIGN]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR] },
  [Resource.SETTINGS_QR_DESIGN_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR] },
  [Resource.SETTINGS_QR_DOMAIN]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR] },
  [Resource.SETTINGS_QR_DOMAIN_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR] },
  [Resource.SETTINGS_QR_POWER_TAG]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.QR] },
  [Resource.SETTINGS_QR_POWER_TAG_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.QR] },
  [Resource.SETTINGS_SIGNAGE_LAYOUT]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE] },
  [Resource.SETTINGS_SIGNAGE_LAYOUT_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE] },
  [Resource.SETTINGS_SIGNAGE_PEOPLE_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PPT] },
  [Resource.SETTINGS_SIGNAGE_PEOPLE_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.PPT] },
  [Resource.SETTINGS_SIGNAGE_PLACES_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PPT] },
  [Resource.SETTINGS_SIGNAGE_PLACES_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.PPT] },
  [Resource.SETTINGS_SIGNAGE_THINGS_PROPERTY]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.PPT] },
  [Resource.SETTINGS_SIGNAGE_THINGS_PROPERTY_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.PPT] },
  [Resource.SETTINGS_USER_PROFILE_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE], products: [] },
  [Resource.SIGNAGES_PEOPLE]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE, Product.PPT] },
  [Resource.SIGNAGES_PEOPLE_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE, Product.PPT] },
  [Resource.SIGNAGES_PLACES]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE, Product.PPT] },
  [Resource.SIGNAGES_PLACES_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE, Product.PPT] },
  [Resource.SIGNAGES_THINGS]: { type: 'collection', actions: [Action.LIST, Action.VIEW, Action.CREATE, Action.UPDATE, Action.DELETE, Action.EXPORT, Action.IMPORT], products: [Product.SIGNAGE, Product.PPT] },
  [Resource.SIGNAGES_THINGS_ITEM]: { type: 'item', actions: [Action.VIEW, Action.UPDATE, Action.DELETE], products: [Product.SIGNAGE, Product.PPT] },
};
