---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  importDerivedRoles:
    - conqrse_roles
  resource: test:resource
  rules:
    - actions: ["*"]
      effect: EFFECT_ALLOW
      derivedRoles:
        - any_user
