---
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
  version: "default"
  resource: "settings:admin:users"
  importDerivedRoles:
    - conqrse_roles
  rules:
    - actions: ["resource:list", "resource:view", "resource:create", "resource:update", "resource:delete", "resource:export", "resource:import"]
      effect: EFFECT_ALLOW
      derivedRoles:
        - root_user
        - platform_administrator
        - agency_owner
        - agency_manager
        - retailer_owner
        - retailer_manager
