---
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
  version: "default"
  resource: "contents:tags:item"
  importDerivedRoles:
    - conqrse_roles
  rules:
    # Retailer access with product subscription check
    - actions: ["view", "update", "delete"]
      effect: EFFECT_ALLOW
      condition:
        match:
          all:
            of:
              - expr: '["brand_center", "compliance", "priceTags", "product", "qr", "signage", "ssp", "trade"].exists(p, p in P.attr.products)'
              - expr: 'P.attr.userLevel == "su" || (P.attr.userLevel == "agency" && ((has(R.attr.agencyId) && P.attr.agencyId == R.attr.agencyId) || (has(R.attr.retailerId) && has(P.attr.retailerId) && P.attr.retailerId == R.attr.retailerId))) || (P.attr.userLevel == "retailer" && has(R.attr.retailerId) && P.attr.retailerId == R.attr.retailerId)'
      derivedRoles:
        - root_user
        - platform_administrator
        - platform_lead
        - platform_member
        - agency_owner
        - agency_manager
        - agency_lead
        - agency_member
        - retailer_owner
        - retailer_manager
        - team_lead
        - staff_operator

    # Collaborators with product subscription check
    - actions: ["view"]
      effect: EFFECT_ALLOW
      condition:
        match:
          all:
            of:
              - expr: '["brand_center", "compliance", "priceTags", "product", "qr", "signage", "ssp", "trade"].exists(p, p in P.attr.products)'
              - expr: 'P.attr.userLevel == "su" || (P.attr.userLevel == "agency" && ((has(R.attr.agencyId) && P.attr.agencyId == R.attr.agencyId) || (has(R.attr.retailerId) && has(P.attr.retailerId) && P.attr.retailerId == R.attr.retailerId))) || (P.attr.userLevel == "retailer" && has(R.attr.retailerId) && P.attr.retailerId == R.attr.retailerId)'
      derivedRoles:
        - root_user
        - platform_administrator
        - platform_lead
        - platform_member
        - platform_collaborator
        - agency_owner
        - agency_manager
        - agency_lead
        - agency_member
        - agency_collaborator
        - guest_collaborator
