---
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
  version: "default"
  resource: "settings:admin_cerbos"
  importDerivedRoles:
    - conqrse_roles
  rules:
    # Cerbos policy settings are restricted to platform administrators
    - actions: ["list", "view", "create", "update", "delete", "export", "import"]
      effect: EFFECT_ALLOW
      derivedRoles:
        - root_user
        - platform_administrator
