---
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
  version: "default"
  resource: "permission"
  importDerivedRoles:
    - conqrse_roles
  rules:
    - actions: ["resource:list", "resource:view", "resource:create", "resource:update", "resource:delete"]
      effect: EFFECT_ALLOW
      derivedRoles:
        - root_user
        - platform_administrator
