---
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
  version: "default"
  resource: "settings:admin_general_retailer:item"
  importDerivedRoles:
    - conqrse_roles
  rules:
    # Admin settings access (all owner/admin at all levels)
    - actions: ["resource:view", "resource:update", "resource:delete"]
      effect: EFFECT_ALLOW
      derivedRoles:
        - root_user
        - platform_administrator
        - agency_owner
        - agency_manager
        - retailer_owner
        - retailer_manager
