apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

namespace: production

replicas:
  - name: cerbos
    count: 3

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: cerbos
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: cerbos.conqrse.com

labels:
  - includeSelectors: true
    pairs:
      environment: production

images:
  - name: ghcr.io/cerbos/cerbos
    newTag: "0.51.0"
