apiVersion: v1
kind: ConfigMap
metadata:
  name: cerbos-config
data:
  cerbos.yaml: |
    server:
      httpListenAddr: "0.0.0.0:3592"
      grpcListenAddr: "0.0.0.0:3593"
      adminAPI:
        enabled: true

    storage:
      driver: "sqlite3"
      sqlite3:
        dsn: "/data/cerbos.db"

    logging:
      level: "info"
