apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-config.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml

configMapGenerator:
  - name: cerbos-policies
    files:
      - _derived_roles.yaml=policies/_derived_roles.yaml
      - resource_product.yaml=policies/resource_product.yaml
      - resource_settings.yaml=policies/resource_settings.yaml
      - resource_profile.yaml=policies/resource_profile.yaml
  - name: cerbos-schemas
    files:
      - principal.json=schemas/principal.json
      - resource_product.json=schemas/resource_product.json
      - resource_settings.json=schemas/resource_settings.json
      - resource_profile.json=schemas/resource_profile.json

commonLabels:
  app: cerbos
