apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-config.yaml
  - configmap-seed-script.yaml
  - seed-job.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml

configMapGenerator:
  - name: cerbos-policies
    options:
      disableNameSuffixHash: true
    files:
      - policies/_derived_roles.yaml
      - policies/resource_admin_settings_general_agency_item.yaml
      - policies/resource_admin_settings_general_ambient_item.yaml
      - policies/resource_admin_settings_general_brand_item.yaml
      - policies/resource_admin_settings_general_retailer_item.yaml
      - policies/resource_connect_contacts_item.yaml
      - policies/resource_connect_contacts.yaml
      - policies/resource_contents_assets_item.yaml
      - policies/resource_contents_assets.yaml
      - policies/resource_contents_backgrounds_item.yaml
      - policies/resource_contents_backgrounds_transition_item.yaml
      - policies/resource_contents_backgrounds_transition.yaml
      - policies/resource_contents_backgrounds.yaml
      - policies/resource_contents_channels_item.yaml
      - policies/resource_contents_channels.yaml
      - policies/resource_contents_content_groups_item.yaml
      - policies/resource_contents_content_groups.yaml
      - policies/resource_contents_playlists_item.yaml
      - policies/resource_contents_playlists.yaml
      - policies/resource_contents_tags_assignments_item.yaml
      - policies/resource_contents_tags_assignments.yaml
      - policies/resource_contents_tags_item.yaml
      - policies/resource_contents_tags.yaml
      - policies/resource_contents_templates_item.yaml
      - policies/resource_contents_templates.yaml
      - policies/resource_footprints_endpoints_item.yaml
      - policies/resource_footprints_endpoints.yaml
      - policies/resource_footprints_pricing.yaml
      - policies/resource_footprints_products_item.yaml
      - policies/resource_footprints_products.yaml
      - policies/resource_footprints_sites_item.yaml
      - policies/resource_footprints_sites.yaml
      - policies/resource_qr_campaigns_item.yaml
      - policies/resource_qr_campaigns.yaml
      - policies/resource_qr_media_item.yaml
      - policies/resource_qr_media.yaml
      - policies/resource_qr_site_item.yaml
      - policies/resource_qr_site.yaml
      - policies/resource_qr_templates_item.yaml
      - policies/resource_qr_templates.yaml
      - policies/resource_reports_campaign_compliance_details.yaml
      - policies/resource_reports_campaign_compliance.yaml
      - policies/resource_reports_campaign_performance_maps.yaml
      - policies/resource_reports_content_proof_of_play.yaml
      - policies/resource_reports_export.yaml
      - policies/resource_reports_media_performance_maps.yaml
      - policies/resource_reports_qrperformance_sitetosite.yaml
      - policies/resource_reports_qrperformance.yaml
      - policies/resource_reports_site_performance_maps.yaml
      - policies/resource_settings_admin_cerbos_item.yaml
      - policies/resource_settings_admin_cerbos.yaml
      - policies/resource_settings_admin_teams_item.yaml
      - policies/resource_settings_admin_teams.yaml
      - policies/resource_settings_admin_users_item.yaml
      - policies/resource_settings_admin_users.yaml
      - policies/resource_settings_footprints_products_pricinggroup_item.yaml
      - policies/resource_settings_footprints_products_pricinggroup.yaml
      - policies/resource_settings_footprints_products_property_item.yaml
      - policies/resource_settings_footprints_products_property.yaml
      - policies/resource_settings_footprints_sites_property_item.yaml
      - policies/resource_settings_footprints_sites_property.yaml
      - policies/resource_settings_qr_defaultredirect_item.yaml
      - policies/resource_settings_qr_defaultredirect.yaml
      - policies/resource_settings_qr_design_item.yaml
      - policies/resource_settings_qr_design.yaml
      - policies/resource_settings_qr_domain_item.yaml
      - policies/resource_settings_qr_domain.yaml
      - policies/resource_settings_qr_powertag_item.yaml
      - policies/resource_settings_qr_powertag.yaml
      - policies/resource_settings_signage_layout_item.yaml
      - policies/resource_settings_signage_layout.yaml
      - policies/resource_settings_signage_people_property_item.yaml
      - policies/resource_settings_signage_people_property.yaml
      - policies/resource_settings_signage_places_property_item.yaml
      - policies/resource_settings_signage_places_property.yaml
      - policies/resource_settings_signage_things_property_item.yaml
      - policies/resource_settings_signage_things_property.yaml
      - policies/resource_settings_user_profile_item.yaml
      - policies/resource_signages_people_item.yaml
      - policies/resource_signages_people.yaml
      - policies/resource_signages_places_item.yaml
      - policies/resource_signages_places.yaml
      - policies/resource_signages_things_item.yaml
      - policies/resource_signages_things.yaml

images:
  - name: ghcr.io/cerbos/cerbos
    newTag: "0.51.0"

labels:
  - includeSelectors: true
    pairs:
      app: cerbos
      version: v1
