apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-config.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - secret.yaml


images:
  - name: ghcr.io/cerbos/cerbos
    newTag: "0.51.0"

labels:
  - includeSelectors: true
    pairs:
      app: cerbos
      version: v1
