apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerbos-policies
  namespace: cerbos-base  # Will be replaced by overlays
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
