apiVersion: v1
kind: Secret
metadata:
  name: cerbos-admin-credentials
type: Opaque
stringData:
  username: cerbos
  passwordHash: JDJ5JDEwJHhvTjd2RjhlNEVZa3hmdVFYMWlrME9XOWNDemV5RzlYcERTYUNHVWZkcWo2ODdRdkhIcUcyCgo=
