apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

namespace: staging

replicas:
  - name: cerbos
    count: 1

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: cerbos
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging-cerbos.conqrse.com

  - target:
      kind: ConfigMap
      name: cerbos-config
    patch: |-
      - op: replace
        path: /data/cerbos.yaml
        value: |
          server:
            apiExplorerEnabled: true
            httpListenAddr: "0.0.0.0:3592"
            grpcListenAddr: "0.0.0.0:3593"
            adminAPI:
              enabled: true
              adminCredentials:
                username: cerbos
                passwordHash: JDJ5JDEwJHhvTjd2RjhlNEVZa3hmdVFYMWlrME9XOWNDemV5RzlYcERTYUNHVWZkcWo2ODdRdkhIcUcyCgo=
            cors:
              allowedOrigins:
                - cerbos
                - cerbos.staging.svc.cluster.local
                - staging-cerbos.conqrse.com
              allowedHeaders:
                - accept
                - content-type
                - user-agent
                - x-requested-with

          storage:
            driver: "sqlite3"
            sqlite3:
              dsn: "/data/cerbos.db"

          logging:
            level: "info"

          telemetry:
            disabled: true

labels:
  - includeSelectors: true
    pairs:
      environment: staging

images:
  - name: ghcr.io/cerbos/cerbos
    newTag: "0.51.0"
